# Generated by Django 2.0.1 on 2018-06-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_auto_20180614_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_ans',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
