# Generated by Django 2.0.1 on 2018-06-16 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_auto_20180616_0226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_text',
        ),
    ]
