# Generated by Django 2.0.1 on 2018-06-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_auto_20180616_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='choice1',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice2',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
